### ISSUE TITLE
Picking up pots

### ISSUE THREAD

**Issue by atticadayz** [WulfMarius/Better-Water-Management#2]
When I press the pick up button the popup interface goes away but the pot is still there. When I leave the house then come back in, the pot is gone but it's not in my inventory. Then when I try to boil snow it won't let me, saying I don't have a pot.

**Comment by WulfMarius** [comment]
Sorry, somehow I missed this one!

I cannot reproduce this here, but I will release version 1.0.2 very shortly.
If you can still reproduce the issue with that version, I'd very much like to get your output log.  
Just try to pick up any pot or pan and when the problem happens again, close the game, and attach the output_log.txt to this issue or upload it somewhere and add a link.

**Comment by TMarkos** [comment]
[output_log.txt](https://github.com/WulfMarius/Better-Water-Management/files/1693495/output_log.txt)

Here's mine, in case he didn't.

**Comment by WulfMarius** [comment]
Thank you for your log, that was quite helpful.  
I could see that you don't have ModComponent installed, which is required for Better-Water-Management.

I suggest reinstalling the latest version including dependencies: https://github.com/WulfMarius/Better-Water-Management/releases/download/1.0.4/Better-Water-Management-with-dependencies-V1.0.4.zip

Let me know if that helps.

I'll also introduce some checks to make sure this issue will be properly reported, instead of causing a glitch.
