### ISSUE TITLE
Game fails to load, v1.30 TLD

### ISSUE THREAD

**Issue by Doomquill** [WulfMarius/Better-Water-Management#7]
Probably not really a bug, I suspect an incompatibility with the newest TLD version.  When I have it installed after the disclaimer screen the music is much louder than it should be, and the game never actually loads up.

**Comment by WulfMarius** [comment]
This is most likely an installation issue.

I recommend using the [Mod-Installer](https://github.com/WulfMarius/Mod-Installer/releases).
Otherwise, the latest versions of ModComponent and AssetLoader are to be installed as well.

If that doesn't resolve the issue, the logfile should contain a description of the problem.
On Windows it can be found at C:\users\USERNAME\AppData\LocalLow\Hinterland\TheLongDark\output_log.txt

**Comment by Doomquill** [comment]
Yes, turns out problem was out of date versions of ModComponent and AssetLoader. Sorry for wasting your time.
