### ISSUE TITLE
Cannot get past wintermute tutorial (brewing tea)

### ISSUE THREAD

**Issue by Candlemancer** [WulfMarius/Better-Water-Management#8]
If the mod is enabled and you start a new Wintermute campaign (perhaps just on the highest difficulty?) you cannot get past the tutorial area to continue the campaign. After Will tries to climb the small wall to leave the crash site, he's guaranteed to get a sprained wrist and cannot leave until he brews and drinks some rose hip tea. However, since the tutorial doesn't give Will a water bottle or waterskin, there's no way to brew teas, so they player gets stuck until they freeze to death. 

Logically, it would be nice if there was some way for players to brew tea using boiled water in a recycled can. Without adding a new menu it seems like the easiest way to do this would just be to add a new cooking recipe that lets the player combine empty recycled can + brewable material + 45 minutes to simulate boiling the water and then brewing the tea in the freshly made water. I'm not sure if you'd have to remove the other recipe for teas in this case, or if there's some way to prefer using held water over melting snow. 
    Otherwise, if the player's starting a Wintermute campaign, they could just start with a water bottle / waterskin. This seems simpler, but it removes a lot of the challenge of Better Water Management.

Temporary workaround:
 - Disabling the mod manually until after the tutorial works for this problem.

**Comment by WulfMarius** [comment]
Thanks for the detailed description.

Most of these mods are made for survival mode, so issues with story mode haven't really been on my mind.

I really like the idea with the additional recipe, because this seems like a natural solution (tea bag + vessel + snow + fire + time = tea). I wouldn't even try to remove the original recipe for those situations where you already have clean water and can save some valuabe time.  
Sounds very reasonable IMO.

Unfortunately this cannot be done with a blueprint, so a solution will take some time.

**Comment by WulfMarius** [comment]
Release 2.3.0 introduces the option to cook food without using water and instead spent additional time to melt snow.

Let me know if this works for you.

**Comment by Candlemancer** [comment]
Just finished testing this, and it appears that everything is working great now! You can get past that required segment in Wintermute, and other brewables appeared to work as well.
